### ISSUE TITLE
workspace list error

### ISSUE THREAD

**Issue by leg100** [leg100/otf#127]
```bash
✦ > _build/otf workspaces list --organization automatize
panic: reflect.Set: value of type *otf.Pagination is not assignable to type *dto.Pagination

goroutine 1 [running]:
reflect.Value.assignTo({0x9f4240?, 0xc0002b6000?, 0xc0002b6000?}, {0xabeef9, 0xb}, 0x9f4a40, 0x0)
	/usr/local/go/src/reflect/value.go:3062 +0x2ac
reflect.Value.Set({0x9f4a40?, 0xc000260120?, 0x0?}, {0x9f4240?, 0xc0002b6000?, 0x0?})
	/usr/local/go/src/reflect/value.go:2088 +0xeb
github.com/leg100/otf/http.unmarshalResponse({0xbbfea0?, 0xc000038080}, {0x9f4e40, 0xc000260120?})
	/home/louis/co/otf/http/client.go:412 +0x4c6
github.com/leg100/otf/http.(*client).do(0xc0000cc6e0, {0xbc4ab0?, 0xc00021e080}, 0xc00025e100, {0x9f4e40, 0xc000260120})
	/home/louis/co/otf/http/client.go:287 +0x4c5
github.com/leg100/otf/http.(*workspaces).List(0xc000266078, {0xbc4ab0, 0xc00021e080}, {{0x0, 0x0}, {0x0, 0x0}, 0xc0000fd1a0, 0x0})
	/home/louis/co/otf/http/workspace_client.go:79 +0x185
main.WorkspaceListCommand.func1(0xc000192a00, {0xabbb14?, 0x2?, 0x2?})
	/home/louis/co/otf/cmd/otf/workspace_list.go:25 +0x8d
github.com/spf13/cobra.(*Command).execute(0xc000192a00, {0xc00007afa0, 0x2, 0x2})
	/home/louis/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00015db80)
	/home/louis/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x39c
github.com/spf13/cobra.(*Command).Execute(...)
	/home/louis/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/louis/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:890
main.Run({0xbc4ab0?, 0xc00021e080}, {0xc00001e0b0, 0x4, 0x4})
	/home/louis/co/otf/cmd/otf/main.go:51 +0x253
main.main()
	/home/louis/co/otf/cmd/otf/main.go:17 +0x85
```

**Comment by leg100** [comment]
Fixed by d241202
