### ISSUE TITLE
Question: Is vcs-xxxxxxxx the OAuth Token ID in OTF?

### ISSUE THREAD

**Issue by Spritekin** [leg100/otf#469]
Hi,
I'm reading the OTF code specifically trying to understand the Workspace Creation API. It looks quite compatible, however at line 85 in workspaces.go it reads: https://github.com/leg100/otf/blob/07ef459384d989f919d75829d8ae35eb80136cc2/internal/api/workspace.go#LL85C21-L85C21

```
		if params.VCSRepo.Identifier == nil || params.VCSRepo.OAuthTokenID == nil {
			err := errors.New("must specify both oauth-token-id and identifier attributes for vcs-repo")
			Error(w, err)
			return
		}
		opts.ConnectOptions = &workspace.ConnectOptions{
			RepoPath:      *params.VCSRepo.Identifier,
			VCSProviderID: *params.VCSRepo.OAuthTokenID,
		}
```

So I Terraform Cloud we had the OAuth Token ID which is defined as: ot-xxxxx (i.e. ot-JvMc15NBoUAvQJiD). However from. the code above it looks like in OTF we should use the VCS code like vcs-xxxxxxxx (i.e. vcs-C06aynAJXWi9MdD4).

Is this correct?

**Comment by leg100** [comment]
Hello @Spritekin. A very good question. Yes, yes it is.

The reason for the deviation from TFC: I didn't quite see the point of the concept of an OAuth Token, or indeed an OAuth Client. Hence I've only implemented VCS Providers.

I should document this as it isn't obvious. I've been intending to document the API, perhaps a compatibility matrix, showing which APIs are implemented, and where there are deviations, such as in this case.

**Comment by Spritekin** [comment]
That would be a nice contribution point. I have little time for coding lately but I could add to some docs as I explore OTF.

**Comment by Spritekin** [comment]
I tried to use python terrasnek with OTF but for some reason it wouldn't work. So I decided to write a very lightweight replacement for terrasnek and is working nicely. It is not complete at all and I only plan to implement the functions I need for my work, but could be a contribution point.

[oss_otf.py.txt](https://github.com/leg100/otf/files/11782961/oss_otf.py.txt)

**Comment by Spritekin** [comment]
Here for those who prefer not downloading such file
```
# This is a library of functions OSS uses to talk to OTF
## While OTF is very close to TFC (including API), it diverges in some points so some libraries like
##  Terrasnek can't work with it.
########################################################################################################################
import urllib, json, requests, logging
import http.client as http_client

# Front facing class
class OTF:
    scheme = "https"
    hostname = ""
    token = ""
    org = ""
    workspaces = None
    workspace_vars = None
    def __init__(self, hostname, token, scheme="https"):

        # Enable for added log verbosity
        #http_client.HTTPConnection.debuglevel = 1 
        # You must initialize logging, otherwise you'll not see debug output.
        #logging.basicConfig()
        #logging.getLogger().setLevel(logging.DEBUG)
        #requests_log = logging.getLogger("requests.packages.urllib3")
        #requests_log.setLevel(logging.DEBUG)
        #requests_log.propagate = True

        # If the hostname includes the scheme, parse it
        if hostname.startswith("http"):
            o = urllib.parse.urlsplit(hostname)
            self.scheme = o.scheme
            self.hostname = o.hostname
        else:
            self.hostname = hostname
            self.schema = scheme
        self.token = token
        self.workspaces = otf_workspaces(self)
        self.workspace_vars = otf_workspace_vars(self)

    # Set the organisation
    def set_org(self, org):
        self.org = org

# Super class to handle endpoints
# Will be inherited by specific implementations
class otf_endpoint:
    otf = None

    def __init__(self, otf):
        self.otf = otf

    def headers(self):
        headers = {
            'Authorization': "Bearer %s" % self.otf.token,
            'Content-Type': "application/vnd.api+json",
        }
        return headers

    def url(self, uri):
        return "%s://%s%s" % (self.otf.scheme, self.otf.hostname, uri)

    # Common get query
    def get(self, uri):
        r = requests.get(url = self.url(uri), headers = self.headers())
        return r.json()

    # Common post query
    def post(self, uri, payload):
        r = requests.post(url = self.url(uri), data = json.dumps(payload), headers = self.headers())
        return r.json()


# Class to handle the workspaces endpoints
class otf_workspaces(otf_endpoint):
    def __init__(self, otf):
        super().__init__(otf)

    def list(self):
        """List the workspaces in an organisation
        """
        return self.get("/api/v2/organizations/%s/workspaces" % self.otf.org )

    def create(self, payload):
        """Creates a workspace and returns the new workspace info
        Deviation from TFC:
            data.attibutes.vcs-repo.oauth-token-id
            When registering a workspace with a VCS provider use the OTF VCS connection identifier (vcs-xxxxxx)
             instead of the TFC Organisation Token (ot-xxxxx) 
        """
        return self.post("/api/v2/organizations/%s/workspaces" % self.otf.org, payload )

# Inner class to handle the workspaces variables
class otf_workspace_vars(otf_endpoint):
    def __init__(self, otf):
        super().__init__(otf)

    def create(self, workspace_id, payload):
        """Create a new environment variable for a workspace
        """
        return self.post("/api/v2/workspaces/%s/vars" % workspace_id, payload )

# Inner class to handle the workspace runs
class otf_runs(otf_endpoint):
    def __init__(self, otf):
        super().__init__(otf)

    def create(self, payload):
        """Create a new run
        The workspace information is defined in the payload.
        """
        return self.post("/api/v2/runs" % self.otf.org, payload )


# Usage example:
#    # Initialise class
#    otf = OTF("https://otf.myhost.com", "MyOTFAPIAccessTokenGenerateItInOTF")
#    otf.set_org("Spritekin")
#
#    # List workspaces
#    workspaces = otf.workspaces.list()
#
#    # Payload to build a new workspace connected to a VCS repo
#    # Create the VCS connection in OTF and use the identifier
#    payload = {
#      "data": {
#        "attributes": {
#          "name": "my-new-workspace",
#          "auto-apply": True,
#          "resource-count": 0,
#          "terraform_version": "1.3.0",
#          "trigger-patterns": ["/trigger.tf"],
#          "vcs-repo": {
#            "identifier": "spritekin/my-vcs-repository",
#            "oauth-token-id": "vcs-12345678910a",
#            "branch": ""
#          }
#        },
#        "type": "workspaces"
#      }
#    }
#    result = otf.workspaces.create(payload)
```

**Comment by leg100** [comment]
@Spritekin Thanks, much appreciated. Could you possibly send across any logs you have from terrasnek or from OTF, that might help diagnose why terrasnek is not working with OTF? It would be good to identify the cause.

**Comment by Spritekin** [comment]
Here is a small program that uses terrasnek (pip install terrasnek first)
[terra.py.txt](https://github.com/leg100/otf/files/11788718/terra.py.txt)

```
% python terra.py --token eyMYOTFAPITOKENF7lglc --host https://otf.my.host.com
Traceback (most recent call last):
  File "/Users/guimo/terraform-oss-platform/terra.py", line 15, in <module>
    workspaces = tfc.workspaces.list()
  File "/Users/guimo/venv/lib/python3.9/site-packages/terrasnek/workspaces.py", line 89, in list
    return self._list(self._org_api_v2_base_url, \
  File "/Users/guimo/venv/lib/python3.9/site-packages/terrasnek/endpoint.py", line 344, in _list
    return self._get(url, query=query, filters=filters, page=page, \
  File "/Users/guimo/venv/lib/python3.9/site-packages/terrasnek/endpoint.py", line 187, in _get
    err = json.loads(req.content.decode("utf-8"))
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```
