### ISSUE TITLE
local, and agent execution mode results in unhandled panic when using terraform v1.6.X

### ISSUE THREAD

**Issue by robbert229** [leg100/otf#626]
When I attempt to use the agent, or local application execution mode for a given workspace I am seeing the cli hang, and eventually crash. Digging into the logs I find that there is uncaught panic occurring. This seems to be new to the latest release.

```terraform
terraform {
  required_providers {
    random = {
      source = "hashicorp/random"
      version = "3.4.3"
    }
  }

    cloud {
    hostname = "blah"
    organization = "home"

    workspaces {
      name = "0001-test"
    }
  }
}

resource "random_password" "test" {
    length = 30
}
```

```
otf         | 2023/10/23 23:30:48 runtime error: invalid memory address or nil pointer dereference
otf         | 2023/10/23 23:30:48 goroutine 1977 [running]:
otf         | runtime/debug.Stack()
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x5e
otf         | github.com/gorilla/handlers.recoveryHandler.log({{0x18a1b40, 0xc014e43a58}, {0x0, 0x0}, 0x1}, {0xc0006698d0?, 0xc000ac6300?, 0x18c2548?})
otf         |   /home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/recovery.go:89 +0xb8
otf         | github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1()
otf         |   /home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/recovery.go:74 +0xbe
otf         | panic({0x13b3020?, 0x231e990?})
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:914 +0x21f
otf         | github.com/leg100/otf/internal/state.(*tfe).createVersion(0xc000ac4de0, {0x18ace30, 0xc014680e00}, 0xc0006a9f00)
otf         |   /home/runner/work/otf/otf/internal/state/tfe.go:74 +0xf2
otf         | net/http.HandlerFunc.ServeHTTP(0xc0006a8100?, {0x18ace30?, 0xc014680e00?}, 0xc000241b20?)
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:2136 +0x29
otf         | github.com/leg100/otf/internal/tokens.NewService.newMiddleware.func1.1({0x18ace30, 0xc014680e00}, 0xc0006a8100)
otf         |   /home/runner/work/otf/otf/internal/tokens/middleware.go:107 +0x277
otf         | net/http.HandlerFunc.ServeHTTP(0x1503120?, {0x18ace30?, 0xc014680e00?}, 0xf?)
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:2136 +0x29
otf         | github.com/leg100/otf/internal/http.NewServer.func4.1({0x18ace30, 0xc014680e00}, 0xc0006a8100)
otf         |   /home/runner/work/otf/otf/internal/http/server.go:137 +0x1d7
otf         | net/http.HandlerFunc.ServeHTTP(0xc018a75990?, {0x18ace30?, 0xc014680e00?}, 0x100?)
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:2136 +0x29
otf         | github.com/gorilla/handlers.recoveryHandler.ServeHTTP({{0x18a1b40, 0xc014e43a58}, {0x0, 0x0}, 0x1}, {0x18ace30?, 0xc014680e00?}, 0x1898128?)
otf         |   /home/runner/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/recovery.go:78 +0xd9
otf         | github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000f00, {0x18ace30, 0xc014680e00}, 0xc0005ff200)
otf         |   /home/runner/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1c5
otf         | net/http.serverHandler.ServeHTTP({0x18a9548?}, {0x18ace30?, 0xc014680e00?}, 0x6?)
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:2938 +0x8e
otf         | net/http.(*conn).serve(0xc0175882d0, {0x18b1320, 0xc014527ce0})
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:2009 +0x5f4
otf         | created by net/http.(*Server).Serve in goroutine 107
otf         |   /opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:3086 +0x5cb
```

**Comment by robbert229** [comment]
After some poking I am seeing that in [internal/state/tfe.go](https://github.com/leg100/otf/blob/aba1cb6539f267bb14edd7f5394d5ef516c791bb/internal/state/tfe.go#L71) opts.State is nil when dereferenced.

```go
func (a *tfe) createVersion(w http.ResponseWriter, r *http.Request) {
	/* ... */

        // opts.State is nil, this is what is causing the panic, and crash.

	// base64-decode state to []byte
	decoded, err := base64.StdEncoding.DecodeString(*opts.State)
	if err != nil {
		tfeapi.Error(w, err)
		return
	}

	/* ... */
```

**Comment by robbert229** [comment]
Figured it out. In `v202310-1` of the state versions api it looks like `state` is now an optional field. The cli is now not sending it, and as a things are kersploding.


https://developer.hashicorp.com/terraform/enterprise/api-docs/state-versions

| New | Old |
|------|----|
| ![image](https://github.com/leg100/otf/assets/3454480/0f33d558-5389-47d7-8670-bcdfc4bda149) | ![image](https://github.com/leg100/otf/assets/3454480/5bc38714-edea-4bf3-8783-a65a3f93c243) |

Reverting to a release from before 1.6.0 is a temporary workaround.

**Comment by robbert229** [comment]
fyi @leg100

**Comment by leg100** [comment]
Are you using the latest release of OTF, v0.1.14, or the HEAD of master? I can re-create the error when using local execution mode with v0.1.4, but I can only re-create the error for _agent_ execution mode with HEAD.

So I can re-create both errors, but I think they have different causes.

**Comment by robbert229** [comment]
> Are you using the latest release of OTF, v0.1.14, or the HEAD of master? I can re-create the error when using local execution mode with v0.1.4, but I can only re-create the error for _agent_ execution mode with HEAD.
> 
> So I can re-create both errors, but I think they have different causes.

I was on my local dev fork somewhere inbetween v0.1.14 and HEAD.
